import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGovernmentCommunicationProduction } from './government-communications-analysis'

export const GOVERNMENT_COMMUNICATION_RECORD_CATEGORIES = ['emails','email-attachments','text-messages','agency-messaging','letters-and-memos','internal-correspondence','meeting-follow-up','calendar-and-invitation-records','communications-with-outside-parties','communication-search-metadata'] as const
export const GOVERNMENT_COMMUNICATION_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']
export const GOVERNMENT_COMMUNICATION_INTAKE = [
  { id:'agency', label:'Agency / jurisdiction', required:true, helpText:'Government agency or public body holding the communications.' },
  { id:'department', label:'Likely office / custodian', helpText:'Department, division, project team, records office, or other likely custodian.' },
  { id:'custodians', label:'People / custodians', helpText:'Officials, employees, contractors, board members, or other people likely to have responsive communications.' },
  { id:'dateStart', label:'Communication start date', required:true, helpText:'Beginning of the requested communication period.' },
  { id:'dateEnd', label:'Communication end date', required:true, helpText:'End of the requested communication period.' },
  { id:'subjectMatter', label:'Subject / project', required:true, helpText:'Plain-English description of the project, decision, property, case, or issue.' },
  { id:'keywords', label:'Search terms', helpText:'Names, phrases, addresses, project names, case numbers, file numbers, or other distinctive terms.' },
  { id:'externalParties', label:'Outside parties', helpText:'Contractors, consultants, applicants, attorneys, developers, vendors, or other outside parties.' },
  { id:'systems', label:'Known systems', helpText:'Email, messaging, text, collaboration, calendar, or other systems known to contain communications.' },
] as const
function text(input: Record<string, unknown>, key: string): string | undefined { const raw=input[key]; if(typeof raw!=='string') return undefined; const value=raw.trim(); return value||undefined }
function list(input: Record<string, unknown>, key: string): string[] { const raw=input[key]; if(!Array.isArray(raw)) return []; return raw.filter((v):v is string=>typeof v==='string').map(v=>v.trim()).filter(Boolean) }
function categories(input: Record<string, unknown>): string[] { const raw=input.categories; if(!Array.isArray(raw)) return [...GOVERNMENT_COMMUNICATION_RECORD_CATEGORIES]; const known=new Set(GOVERNMENT_COMMUNICATION_RECORD_CATEGORIES); const selected=raw.filter((v):v is string=>typeof v==='string'&&known.has(v as typeof GOVERNMENT_COMMUNICATION_RECORD_CATEGORIES[number])); return selected.length?selected:[...GOVERNMENT_COMMUNICATION_RECORD_CATEGORIES] }
function describe(category:string,input:Record<string,unknown>):string { const custodians=list(input,'custodians'); const keywords=list(input,'keywords'); const outside=list(input,'externalParties'); const dates=text(input,'dateStart')&&text(input,'dateEnd')?` Cover ${text(input,'dateStart')} through ${text(input,'dateEnd')}.`:''; const constraints=[custodians.length?`custodians ${custodians.join(', ')}`:'',keywords.length?`search terms ${keywords.join(', ')}`:'',outside.length?`outside parties ${outside.join(', ')}`:''].filter(Boolean); const scope=constraints.length?` Search using these constraints: ${constraints.join('; ')}.`:''; const subject=text(input,'subjectMatter')?` The communications concern: ${text(input,'subjectMatter')}.`:''; const map:Record<string,string>={'emails':`Emails sent or received by the identified custodians concerning the specified subject, project, or matter, including relevant threads and messages.${scope}${dates}`,'email-attachments':`Attachments to responsive emails, including documents, spreadsheets, PDFs, images, plans, and other files that form part of the communication record.${scope}${dates}`,'text-messages':`Text messages and SMS/MMS communications on agency-managed devices or systems where maintained and legally requestable.${scope}${dates}`,'agency-messaging':`Messages from agency collaboration or messaging platforms, including chat channels, direct messages, and project workspaces where maintained and responsive.${scope}${dates}`,'letters-and-memos':`Letters, memoranda, notices, and formal written communications concerning the identified subject or matter.${scope}${dates}`,'internal-correspondence':`Internal emails and written correspondence among agency personnel concerning the identified subject, project, case, or decision.${scope}${dates}`,'meeting-follow-up':`Post-meeting emails, notes, action items, follow-up correspondence, and communications documenting decisions or next steps.${scope}${dates}`,'calendar-and-invitation-records':`Calendar entries, meeting invitations, attendee records, and related scheduling metadata concerning the identified subject or matter.${scope}${dates}`,'communications-with-outside-parties':`Communications between agency personnel and identified contractors, consultants, applicants, vendors, developers, attorneys, or other outside parties concerning the matter.${scope}${dates}`,'communication-search-metadata':`Searchable metadata or other records sufficient to identify responsive communication systems, custodians, date ranges, and search scope when maintained and legally requestable.${scope}${dates}`}; return `${map[category]??`Communications concerning ${category}.${scope}${dates}`}${subject}` }
function validateCommunications(request:ValidatedRequest):readonly {field:string;message:string}[]{
  const issues:{field:string;message:string}[]=[]
  let scope:{custodians?:unknown;keywords?:unknown[];externalParties?:unknown[];systems?:unknown[]}={}
  try { const parsed=JSON.parse(request.scope??'{}') as Record<string,unknown>; scope={custodians:parsed.custodians,keywords:Array.isArray(parsed.keywords)?parsed.keywords:[],externalParties:Array.isArray(parsed.externalParties)?parsed.externalParties:[],systems:Array.isArray(parsed.systems)?parsed.systems:[]} } catch { scope={} }
  const hasMeaningfulConstraint=[scope.custodians,scope.keywords,scope.externalParties,scope.systems].some(value=>Array.isArray(value)?value.length>0:typeof value==='string'&&value.trim().length>0)
  if(!hasMeaningfulConstraint) issues.push({field:'searchConstraints',message:'Provide at least one meaningful search constraint such as a custodian, distinctive keyword, outside party, project identifier, or known communication system.'})
  const descriptions=request.items.map(i=>i.description.toLowerCase()).join(' ')
  if(!descriptions.includes('communications concern')) issues.push({field:'subjectMatter',message:'Describe the subject, project, decision, case, property, or issue the communications concern.'})
  return issues
}
export function buildGovernmentCommunicationsRequest(input:Record<string,unknown>) { const subject=text(input,'subjectMatter'); const selected=categories(input); const start=text(input,'dateStart'); const end=text(input,'dateEnd'); const title=`Government Communications — ${subject??'Subject Matter'}`; const agency=text(input,'agency')??''; return { title, normalizedTitle:title.trim().replace(/\s+/g,' '), agency, normalizedAgency:agency.trim().replace(/\s+/g,' '), jurisdiction:text(input,'jurisdiction'), purpose:text(input,'purpose')??'Identify and obtain responsive government communications associated with the specified subject, custodians, search terms, and date range.', scope:JSON.stringify({workflow:'government-communications-records',department:text(input,'department'),custodians:list(input,'custodians'),dateStart:start,dateEnd:end,subjectMatter:subject,keywords:list(input,'keywords'),externalParties:list(input,'externalParties'),systems:list(input,'systems')}), items:selected.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'department'),systemHint:text(input,'systems')||undefined,format:['emails','email-attachments','text-messages','agency-messaging'].includes(category)?'native electronic format with metadata where available':undefined})) } }
export const GOVERNMENT_COMMUNICATION_FINDINGS=['MISSING_REQUESTED_CATEGORY','CUSTODIAN_GAP','SEARCH_SCOPE_AMBIGUITY','REFERENCED_ATTACHMENT_NOT_PRODUCED','DATE_GAP','DUPLICATE_RECORD','THREAD_GAP','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const
export const governmentCommunicationsRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({ id:'government-communications-records', name:'Government Emails & Communications Records Request', description:'Build a targeted public-records request for government emails, attachments, texts, messaging, letters, meeting follow-up, calendars, and communications with outside parties.', searchIntent:'government email records request', seo:{title:'Government Emails & Communications Records Request',description:'Build a targeted government communications records request for emails, attachments, texts, messaging, calendars, and communications using custodians, keywords, projects, and date ranges.',canonicalPath:'/workflows/government-communications-records'}, intakeVersion:'1.0.0', intake:GOVERNMENT_COMMUNICATION_INTAKE, capabilities:GOVERNMENT_COMMUNICATION_CAPABILITIES, request:{categories:GOVERNMENT_COMMUNICATION_RECORD_CATEGORIES,build:buildGovernmentCommunicationsRequest}, validate:validateCommunications, responseAnalysis:{findingTypes:GOVERNMENT_COMMUNICATION_FINDINGS, async analyze(input:unknown){ if(!input||typeof input!=='object') throw new Error('GOVERNMENT_COMMUNICATION_PRODUCTION_ANALYSIS_INPUT_INVALID'); const source=input as {requestedItems?:readonly {category:string;description:string}[]; records?:readonly {id:string;filename:string;category?:string;text?:string;sha256?:string;threadId?:string}[]}; const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(Boolean).slice(0,20)})); return analyzeGovernmentCommunicationProduction(requested,source.records??[]) } } })
