import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import { analyzePoliceProduction, type PoliceProductionRecord, type PoliceProductionIdentifiers } from './police-records-analysis'
import { buildPoliceRecordsTimeline } from './police-records-timeline'
import type { RecordsDomainCapability } from './domain-pack'

export const POLICE_RECORD_CATEGORIES = [
  'incident-report','arrest-records','dispatch-cad','body-camera','dash-camera','911-calls','photographs-and-video','witness-and-victim-statements','supplemental-reports','correspondence-and-case-notes',
] as const
export const POLICE_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']
export const POLICE_INTAKE = [
  { id:'agency', label:'Agency', required:true, helpText:'Police department, sheriff, state police, campus police, or other law-enforcement custodian.' },
  { id:'department', label:'Likely unit / custodian', helpText:'Patrol, investigations, records, traffic, communications, professional standards, or another likely unit.' },
  { id:'incidentDateStart', label:'Incident start date', required:true, helpText:'Beginning of the relevant incident window.' },
  { id:'incidentDateEnd', label:'Incident end date', required:true, helpText:'End of the relevant incident window.' },
  { id:'incidentNumber', label:'Incident / report number', helpText:'Incident, case, CAD, report, or event number when known.' },
  { id:'arrestNumber', label:'Arrest / booking number', helpText:'Arrest, booking, or jail identifier when known.' },
  { id:'location', label:'Incident location', helpText:'Exact address, intersection, business, or other identifiable location.' },
  { id:'person', label:'Person involved', helpText:'Subject, victim, witness, officer, or other person associated with the incident.' },
  { id:'vehicle', label:'Vehicle identifier', helpText:'Plate, VIN, unit number, or other vehicle identifier when relevant.' },
  { id:'subjectMatter', label:'Incident or subject matter', required:true, helpText:'Plain-English description of what happened or which incident you are trying to identify.' },
] as const
function text(input: Record<string, unknown>, key: string): string | undefined { const raw=input[key]; if(typeof raw!=='string') return undefined; const trimmed=raw.trim(); return trimmed||undefined }
function categories(input: Record<string, unknown>): string[] { const raw=input.categories; if(!Array.isArray(raw)) return [...POLICE_RECORD_CATEGORIES]; const known=new Set(POLICE_RECORD_CATEGORIES); const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof POLICE_RECORD_CATEGORIES[number])); return selected.length?selected:[...POLICE_RECORD_CATEGORIES] }
function describe(category:string,input:Record<string,unknown>):string { const identifiers=[text(input,'incidentNumber')&&`incident/report number ${text(input,'incidentNumber')}`,text(input,'arrestNumber')&&`arrest/booking number ${text(input,'arrestNumber')}`,text(input,'location')&&`location ${text(input,'location')}`,text(input,'person')&&`person ${text(input,'person')}`,text(input,'vehicle')&&`vehicle identifier ${text(input,'vehicle')}`].filter(Boolean); const dates=text(input,'incidentDateStart')&&text(input,'incidentDateEnd')?` Cover ${text(input,'incidentDateStart')} through ${text(input,'incidentDateEnd')}.`:''; const scope=identifiers.length?` Search using these identifiers: ${identifiers.join('; ')}.`:''; const subject=text(input,'subjectMatter')?` The incident concerns: ${text(input,'subjectMatter')}.`:''; const descriptions:Record<string,string>={'incident-report':`Incident, offense, or case reports and all report versions associated with the identified incident.${scope}${dates}`,'arrest-records':`Arrest reports, booking records, charging information, custody records, and related arrest documentation tied to the identified matter.${scope}${dates}`,'dispatch-cad':`Computer-aided dispatch records, call-for-service entries, unit assignments, timestamps, disposition codes, and related CAD history.${scope}${dates}`,'body-camera':`Body-worn camera recordings and associated metadata, indexes, evidence references, retention identifiers, and redaction/withholding records.${scope}${dates}`,'dash-camera':`In-car or dash-camera recordings and associated metadata, indexes, evidence references, retention identifiers, and redaction/withholding records.${scope}${dates}`,'911-calls':`911 calls, emergency communications, call logs, recordings, and related dispatch communications maintained by the agency.${scope}${dates}`,'photographs-and-video':`Photographs, scene video, surveillance media, evidence images, and associated metadata maintained with or referenced by the incident file.${scope}${dates}`,'witness-and-victim-statements':`Witness statements, victim statements, recorded interviews, interview summaries, and related documentation.${scope}${dates}`,'supplemental-reports':`Supplemental reports, follow-up reports, investigative supplements, evidence logs, and later-added case documentation.${scope}${dates}`,'correspondence-and-case-notes':`Correspondence, case notes, documented communications, referrals, and other case-management records maintained as part of the incident file.${scope}${dates}`}; return `${descriptions[category]??`Records concerning ${category}.${scope}${dates}`}${subject}` }
function validatePolice(request:ValidatedRequest):readonly {field:string;message:string}[]{ const issues:{field:string;message:string}[]=[]; const descriptions=request.items.map(item=>item.description.toLowerCase()).join(' '); if(!descriptions.includes('location')&&!descriptions.includes('incident/report number')&&!descriptions.includes('person ')) issues.push({field:'identifiers',message:'Provide an incident/report number, location, or person involved so the agency can identify the event.'}); if(!descriptions.includes('incident concerns')) issues.push({field:'subjectMatter',message:'Describe the incident or subject matter in plain language.'}); return issues }
export function buildPoliceRecordsRequest(input:Record<string,unknown>){ const agency=text(input,'agency')??''; const incidentNumber=text(input,'incidentNumber'); const location=text(input,'location'); const person=text(input,'person'); const subject=text(input,'subjectMatter'); const start=text(input,'incidentDateStart'); const end=text(input,'incidentDateEnd'); const selected=categories(input); return {title:`Police Records — ${incidentNumber??location??person??subject??'Incident'}`,agency,jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Identify and document the law-enforcement records associated with the specified incident or event.',scope:JSON.stringify({workflow:'police-records',incidentNumber,arrestNumber:text(input,'arrestNumber'),location,person,vehicle:text(input,'vehicle'),department:text(input,'department'),incidentDateStart:start,incidentDateEnd:end,subjectMatter:subject}),items:selected.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'department'),systemHint:category==='dispatch-cad'?'CAD / call-for-service system':category==='body-camera'?'body-worn camera evidence system':undefined,format:category==='body-camera'||category==='dash-camera'||category==='911-calls'?'native digital files where available':undefined}))} }
export const POLICE_ANALYSIS_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','INCIDENT_IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_MEDIA','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const
export const policeRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({id:'police-records',name:'Police Records Request',description:'Build a targeted police records request for incident reports, dispatch, arrests, body-camera, dash-camera, 911, photographs, statements, supplements, and case records.',searchIntent:'police records request',seo:{title:'Police Records Request — Incident Reports, CAD & Body-Camera Records',description:'Build a targeted police records request using incident numbers, dates, locations, people, vehicles, and specific record categories.',canonicalPath:'/workflows/police-records'},intakeVersion:'1.0.0',intake:POLICE_INTAKE,capabilities:POLICE_RECORD_CAPABILITIES,request:{categories:POLICE_RECORD_CATEGORIES,build:buildPoliceRecordsRequest},validate:validatePolice,responseAnalysis:{findingTypes:POLICE_ANALYSIS_FINDINGS,async analyze(input:unknown){ if(!input||typeof input!=='object') throw new Error('POLICE_PRODUCTION_ANALYSIS_INPUT_INVALID'); const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly PoliceProductionRecord[];identifiers?:PoliceProductionIdentifiers}; const analysis=analyzePoliceProduction((source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(Boolean).slice(0,16)})),source.records??[],source.identifiers??{}); return {...analysis,timeline:buildPoliceRecordsTimeline(source.records??[])}; }}})