import { runMultiLlm, type LlmProvider, type MultiLlmPolicy } from '../ai/multi-llm-orchestrator'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'
import type { PropertyPermitProductionRecord } from './property-permit-analysis'

export type PropertyPermitFacts = { permitNumbers:string[]; applicationNumbers:string[]; parcelNumbers:string[]; addresses:string[]; dates:string[]; applicants:string[]; contractors:string[] }
export type PropertyPermitClassification = { category:string; rationale:string }
export type PropertyPermitStrategy = { likelyCustodians:string[]; searchTerms:string[]; identifiersToConfirm:string[]; scopeGaps:string[]; missingRecordPriorities:string[]; followUpPriorities:string[] }
const arrays=(v:unknown,k:string)=>{if(!Array.isArray(v)||v.some(x=>typeof x!=='string'))throw new Error(`PROPERTY_PERMIT_AI_SCHEMA_INVALID:${k}`);return v as string[]}
function validateStrategy(v:unknown):PropertyPermitStrategy{if(!v||typeof v!=='object')throw new Error('PROPERTY_PERMIT_AI_SCHEMA_INVALID:object');const c=v as Record<string,unknown>;return {likelyCustodians:arrays(c.likelyCustodians,'likelyCustodians'),searchTerms:arrays(c.searchTerms,'searchTerms'),identifiersToConfirm:arrays(c.identifiersToConfirm,'identifiersToConfirm'),scopeGaps:arrays(c.scopeGaps,'scopeGaps'),missingRecordPriorities:arrays(c.missingRecordPriorities,'missingRecordPriorities'),followUpPriorities:arrays(c.followUpPriorities,'followUpPriorities')}}
export function classifyPropertyPermit(providers:readonly LlmProvider[],record:PropertyPermitProductionRecord,policy:MultiLlmPolicy){return runMultiLlm<PropertyPermitClassification>(providers,'classification',{filename:record.filename,text:record.text??'',category:record.category??''},policy)}
export function extractPropertyPermitFacts(providers:readonly LlmProvider[],record:PropertyPermitProductionRecord,policy:MultiLlmPolicy){return runMultiLlm<PropertyPermitFacts>(providers,'extraction',{filename:record.filename,text:record.text??'',category:record.category??''},policy)}
export function assessPropertyPermitContradiction(providers:readonly LlmProvider[],left:PropertyPermitProductionRecord,right:PropertyPermitProductionRecord,policy:MultiLlmPolicy){return runMultiLlm<{contradictory:boolean;explanation:string}>(providers,'contradiction',{left:{id:left.id,text:left.text??''},right:{id:right.id,text:right.text??''}},policy)}
export async function runPropertyPermitStrategy(input:unknown){const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)throw new Error(`PROPERTY_PERMIT_LLM_QUORUM_NOT_MET:${providers.length}/2`);const result=await runMultiLlm<PropertyPermitStrategy>(providers,'strategy',input,{minimumProviders:2,agreementThreshold:0.67,maxProviders:3});return {...result,value:validateStrategy(result.value)}}
