import { describe, expect, vi, it } from 'vitest'
import type { LlmProvider, LlmTask } from '../ai/multi-llm-orchestrator'

const completeTask=(provider:'gemini'|'openai',task:LlmTask)=>{const shared={provider:`test-${provider}`,model:`test-${provider}`,confidence:0.95,warnings:[] as string[]};if(task==='classification')return {...shared,value:{category:'building-permits',rationale:'Permit record matches the requested permit category.'}};if(task==='extraction')return {...shared,value:{permitNumbers:['BP-2026-10'],applicationNumbers:['APP-10'],parcelNumbers:['APN-123'],addresses:['123 Main St'],dates:['2026-08-01'],applicants:['Example Owner'],contractors:['Example Builder']}};if(task==='contradiction')return {...shared,value:{contradictory:false,explanation:'No contradiction identified.'}};return {...shared,value:{likelyCustodians:['Building Department'],searchTerms:['BP-2026-10','123 Main St','APN-123'],identifiersToConfirm:['permit number','parcel/APN'],scopeGaps:[],missingRecordPriorities:[],followUpPriorities:['confirm complete inspection and plan set production']}}}
const testProviders:LlmProvider[]=(['gemini','openai'] as const).map(provider=>({id:`test-${provider}`,async complete<T>(task:LlmTask){return completeTask(provider,task) as {provider:string;model:string;confidence:number;warnings:string[];value:T}}}))
vi.mock('../ai/records-llm-providers',()=>({getConfiguredRecordsLlmProviders:()=>testProviders}))
import { buildPropertyPermitRecordsRequest, propertyPermitRecordsWorkflow } from './property-permit-records'

describe('property permit workflow integration',()=>{it('runs deterministic analysis plus all four multi-LLM tasks',async()=>{const request=buildPropertyPermitRecordsRequest({agency:'Example Building Department',permitNumber:'BP-2026-10',address:'123 Main St',parcelNumber:'APN-123',dateStart:'2024-01-01',dateEnd:'2026-08-24',projectDescription:'two-story addition'});const result=await propertyPermitRecordsWorkflow.responseAnalysis!.analyze({requestedItems:request.items,records:[{id:'r1',filename:'permit.pdf',category:'building-permits',text:'Permit BP-2026-10 for 123 Main St, APN-123.'},{id:'r2',filename:'inspection.pdf',category:'inspection-records',text:'Inspection for permit BP-2026-10 at 123 Main St.'}]}) as {recordsReviewed:number;aiProvenance:{providers:string[];confidence:number};aiRecordAnalysis:unknown[];aiContradictions:unknown[]};expect(result.recordsReviewed).toBe(2);expect(result.aiProvenance.providers).toEqual(['test-gemini','test-openai']);expect(result.aiProvenance.confidence).toBeGreaterThanOrEqual(0.94);expect(result.aiRecordAnalysis).toHaveLength(2);expect(result.aiContradictions).toHaveLength(0)})
  it('fails closed when fewer than two providers are available',async()=>{const request=buildPropertyPermitRecordsRequest({agency:'Example',permitNumber:'BP-1',address:'123 Main St',dateStart:'2026-01-01',dateEnd:'2026-01-31',projectDescription:'addition'});const module=await import('../ai/records-llm-providers');vi.spyOn(module,'getConfiguredRecordsLlmProviders').mockReturnValue([testProviders[0]]);await expect(propertyPermitRecordsWorkflow.responseAnalysis!.analyze({requestedItems:request.items,records:[]})).rejects.toThrow('PROPERTY_PERMIT_LLM_QUORUM_NOT_MET:1/2')})})
