export type Workflow = {
  slug: string
  title: string
  category: string
  intent: string
  description: string
  bestFor: string[]
  cta: string
  seo?: {
    title: string
    description: string
    keywords: string[]
    faqs: { question: string; answer: string }[]
  }
}

export const workflows: Workflow[] = [
  { slug: 'public-records-request', title: 'Public Records Request', category: 'Start here', intent: 'public records request', description: 'Turn a plain-English objective into a precise request with record categories, date ranges, custodians, identifiers, format requirements, and exclusions.', bestFor: ['General public records', 'Agency records', 'Open records requests'], cta: 'Build a records request' },
  { slug: 'police-records', title: 'Police Records Request', category: 'Law enforcement', intent: 'police records request', description: 'Request incident reports, arrest records, dispatch materials, body-camera records, 911 calls, photographs, and related police records with enough specificity to make the request searchable.', bestFor: ['Incident reports', 'Police reports', 'Arrest and booking records', 'CAD / dispatch records', 'Body- and dash-camera records'], cta: 'Build a Police Records Request', seo: { title: 'Police Records Request — Incident Reports, CAD & Body-Camera Records', description: 'Build a targeted police records request for an incident, arrest, dispatch call, body-camera recording, 911 call, photograph, or related case record.', keywords: ['police records request', 'police report request', 'request police records', 'police public records request', 'police incident report request', 'CAD records request', 'dispatch records request', 'body camera records request', 'bodycam records request', 'dashcam records request', '911 call records request', 'arrest records request', 'police records by incident number', 'police records by date', 'police records by address'], faqs: [
    { question: 'How do I request a police report?', answer: 'Start with the police agency, incident date, location or incident number, and a plain-English description of what happened. Adding people or vehicle identifiers can make the search more precise.' },
    { question: 'Can I request body-camera footage?', answer: 'Potentially. The workflow can specifically identify body-camera records and their associated incident, dates, and identifiers. Whether footage is releasable depends on the agency and applicable law.' },
    { question: 'What if I do not know the incident number?', answer: 'You can still start with the incident date, location, people involved, vehicle identifiers, or a clear description of the event.' },
    { question: 'Can I request 911 calls and dispatch records?', answer: 'Yes, where maintained and legally requestable. The workflow separately identifies 911 communications and CAD/dispatch records so the agency can search the relevant systems.' },
    { question: 'What if the agency sends only the incident report?', answer: 'The original request scope can be preserved so the production can be compared against requested categories such as CAD, recordings, photographs, statements, and supplements.' },
    { question: 'Can police records be redacted or withheld?', answer: 'Yes. Some records or portions may be withheld or redacted under applicable law. The workflow can identify withholding or redaction issues for review without assuming that a withholding is improper.' },
  ] } },
  { slug: 'court-records', title: 'Court Records Request', category: 'Courts', intent: 'how to get court records', description: 'Organize a request for case files, docket materials, filings, exhibits, and other court-held records while preserving case identifiers and date ranges.', bestFor: ['Case files', 'Dockets', 'Court filings', 'Exhibits'], cta: 'Request court records' },
  { slug: 'property-records', title: 'Property & Parcel Records', category: 'Property', intent: 'request property records', description: 'Build a targeted request for property, parcel, assessor, recorder, ownership, and related public records tied to a property or parcel.', bestFor: ['Property files', 'Parcel records', 'Ownership records', 'Recorder records'], cta: 'Request property records' },
  { slug: 'code-enforcement-records', title: 'Code Enforcement Records Request', category: 'Property & Code Enforcement', intent: 'code enforcement records request', description: 'Create a focused public-records request for code violations, complaints, inspections, notices, photographs, permits, citations, communications, and enforcement history for a property or case.', bestFor: ['Code violation histories', 'Inspection records', 'Complaints and photographs', 'Notices, citations and enforcement files', 'Property-specific code records'], cta: 'Build a Code Enforcement Records Request', seo: { title: 'Code Enforcement Records Request — Get Property Violation & Inspection Records', description: 'Create a focused code enforcement records request for property violations, complaints, inspections, notices, permits, citations, photos, and enforcement history. Build and mail your request.', keywords: ['code enforcement records request', 'code enforcement public records request', 'request code enforcement records', 'code violation records request', 'property code enforcement records', 'code enforcement complaint records', 'code enforcement inspection records', 'code violation history request', 'property violation records', 'building code enforcement records', 'code enforcement case records', 'code enforcement records by address', 'code enforcement records by parcel number', 'code enforcement records by case number', 'code enforcement request template'], faqs: [
    { question: 'Can I request code enforcement records for a property?', answer: 'Yes. A focused request can identify the property by address, parcel or APN, case number, violation number, or other identifiers and ask for specific categories of records.' },
    { question: 'What code enforcement records can I request?', answer: 'Depending on the agency, you may request complaints, inspections, photographs or video, notices, citations, orders, permits, correspondence, abatement records, and other identifiable enforcement records.' },
    { question: 'Can I request code enforcement records by address?', answer: 'Yes. An address is often one of the most useful identifiers. Adding an APN, case number, violation number, or date range can make the search more precise.' },
    { question: 'What if I do not know the case number?', answer: 'You can still start with the property address and other known identifiers. The request builder helps organize the available information without requiring every identifier.' },
    { question: 'What if the agency only produces some of the records?', answer: 'The workflow preserves the original request scope so the production can be reviewed for missing categories, references to unproduced records, gaps, and other follow-up issues.' },
    { question: 'What if records are redacted or withheld?', answer: 'The production review can flag withholding or redaction language for review. Any legal conclusion about whether a withholding is proper should be based on the applicable jurisdiction and current law.' },
  ] } },
  { slug: 'permit-inspection-records', title: 'Permit & Inspection Records', category: 'Property', intent: 'permit records request', description: 'Target permits, plans, inspection reports, correction notices, approvals, and related building-department records with project identifiers and date ranges.', bestFor: ['Building permits', 'Inspection reports', 'Plans', 'Correction notices'], cta: 'Request permit records' },
  { slug: 'government-emails', title: 'Government Emails & Communications', category: 'Communications', intent: 'government email records request', description: 'Structure an email and communications request around custodians, domains, date ranges, subjects, projects, and identifiers so the scope is usable by the responding agency.', bestFor: ['Government emails', 'Agency correspondence', 'Text and communication records'], cta: 'Request communications' },
  { slug: 'planning-records', title: 'Planning & Development Records', category: 'Planning', intent: 'planning records request', description: 'Request planning applications, staff reports, zoning materials, development correspondence, meeting records, and related agency files.', bestFor: ['Planning files', 'Zoning records', 'Development applications', 'Staff reports'], cta: 'Request planning records' },
  { slug: 'case-records', title: 'Records About a Specific Case', category: 'Case research', intent: 'records about a specific case', description: 'Build a case-centered request that connects names, addresses, case numbers, dates, departments, and referenced documents into one coherent records scope.', bestFor: ['Enforcement cases', 'Administrative cases', 'Agency investigations', 'Cross-department records'], cta: 'Build a case request' },
  { slug: 'foia-request', title: 'FOIA / Federal Records Request', category: 'Federal', intent: 'how do I file a FOIA request', description: 'Prepare a federal records request with a clear description of the records, date range, custodians or systems when known, and the requester information needed for the agency.', bestFor: ['Federal agencies', 'FOIA requests', 'Federal records'], cta: 'Build a FOIA request' },
]
