export type WorkflowSeo = {
  title: string
  description: string
  keywords: string[]
  faqs: { question: string; answer: string }[]
}

export type Workflow = {
  slug: string
  title: string
  category: string
  intent: string
  description: string
  bestFor: string[]
  cta: string
  seo?: WorkflowSeo
}

const faq = (question: string, answer: string) => ({ question, answer })
const seo = (title: string, description: string, keywords: string[], faqs: WorkflowSeo['faqs']): WorkflowSeo => ({ title, description, keywords, faqs })

export const workflows: Workflow[] = [
  {
    slug: 'public-records-request',
    title: 'Public Records Request',
    category: 'Start here',
    intent: 'public records request',
    description: 'Turn a plain-English objective into a precise request with record categories, date ranges, custodians, identifiers, format requirements, and exclusions.',
    bestFor: ['General public records', 'Agency records', 'Open records requests'],
    cta: 'Build a records request',
    seo: seo(
      'Public Records Request — How to Request Government Records',
      'Build a precise public records request with the agency, records sought, dates, custodians, identifiers, formats, and scope needed for a searchable request.',
      ['public records request', 'public records request template', 'how to make a public records request', 'request public records', 'government records request', 'open records request', 'public information request', 'records request letter', 'public records request form', 'how to request government records'],
      [
        faq('What is a public records request?', 'A public records request asks a government agency for identifiable records it maintains. A strong request clearly describes the records, relevant time period, and useful identifiers or custodians.'),
        faq('What should I include in a public records request?', 'Include the agency, subject or matter, specific record categories, date range, known names or identifiers, preferred format when appropriate, and useful narrowing information.'),
        faq('How do identifiers make a records request easier to search?', 'An address, parcel number, case number, permit number, incident number, person, project name, or other agency identifier can substantially reduce ambiguity and help the custodian locate the right records.'),
        faq('What if the agency produces only part of the request?', 'Keep the original scope and compare the production against it. Missing categories, referenced-but-unproduced records, duplicates, redactions, and other gaps can become targeted follow-up items.'),
      ],
    ),
  },
  {
    slug: 'police-records',
    title: 'Police Records Request',
    category: 'Law enforcement',
    intent: 'police records request',
    description: 'Request incident reports, arrest records, dispatch materials, body-camera records, 911 calls, photographs, and related police records with enough specificity to make the request searchable.',
    bestFor: ['Incident reports', 'Police reports', 'Arrest and booking records', 'CAD / dispatch records', 'Body- and dash-camera records'],
    cta: 'Build a Police Records Request',
    seo: seo(
      'Police Records Request — Incident Reports, CAD & Body-Camera Records',
      'Build a targeted police records request for an incident, arrest, dispatch call, body-camera recording, 911 call, photograph, or related case record.',
      ['police records request', 'police report request', 'request police records', 'police public records request', 'police incident report request', 'CAD records request', 'dispatch records request', 'body camera records request', 'bodycam records request', 'dashcam records request', '911 call records request', 'arrest records request', 'police records by incident number', 'police records by date', 'police records by address'],
      [
        faq('How do I request a police report?', 'Start with the police agency, incident date, location or incident number, and a plain-English description of the event. People or vehicle identifiers can make the request more precise.'),
        faq('Can I request body-camera footage?', 'Potentially. The workflow can identify body-camera records and their associated incident, dates, and identifiers. Whether footage is releasable depends on the agency and applicable law.'),
        faq('Can I request 911 calls and dispatch records?', 'Yes, where maintained and legally requestable. They are separate request categories so the agency can search the relevant systems.'),
        faq('What if I do not know the incident number?', 'Use the incident date, location, people involved, vehicle identifiers, or a clear description of the event.'),
      ],
    ),
  },
  {
    slug: 'court-records',
    title: 'Court Records Request',
    category: 'Courts',
    intent: 'how to get court records',
    description: 'Organize a request for case files, docket materials, filings, exhibits, and other court-held records while preserving case identifiers and date ranges.',
    bestFor: ['Case files', 'Dockets', 'Court filings', 'Exhibits'],
    cta: 'Request court records',
    seo: seo(
      'Court Records Request — Case Files, Dockets, Filings & Exhibits',
      'Build a focused court records request around the court, case number, parties, filing dates, docket entries, filings, exhibits, and other case materials.',
      ['court records request', 'court records request form', 'how to request court records', 'request court case file', 'court case file request', 'docket records request', 'court filing records request', 'court exhibits request', 'case docket request', 'court documents request', 'court records by case number'],
      [
        faq('How do I request a court case file?', 'Identify the court, case number if known, parties, relevant dates, and the specific materials sought. Procedures can differ by court and record type.'),
        faq('Can I request court exhibits?', 'You can specifically identify exhibits, attachments, and filed supporting materials. Availability and copy rules depend on the court and record.'),
        faq('Are all court records public?', 'No. Some records can be restricted, sealed, confidential, or otherwise subject to access limits.'),
        faq('What if I only know the parties and approximate date?', 'Provide the court, parties, approximate filing or hearing period, case type, and any other identifiers you have so the search can be narrowed.'),
      ],
    ),
  },
  {
    slug: 'property-records',
    title: 'Property & Parcel Records',
    category: 'Property',
    intent: 'request property records',
    description: 'Build a targeted request for property, parcel, assessor, recorder, ownership, and related public records tied to a property or parcel.',
    bestFor: ['Property files', 'Parcel records', 'Ownership records', 'Recorder records'],
    cta: 'Request property records',
    seo: seo(
      'Property Records Request — Parcel, Ownership & Property Files',
      'Build a property records request using an address, APN or parcel number, owner, legal description, document number, and date range.',
      ['property records request', 'property records by address', 'property records request by APN', 'parcel records request', 'property ownership records request', 'assessor records request', 'recorder records request', 'property file request', 'property history records', 'real property records request', 'request property records from county'],
      [
        faq('How do I request property records?', 'Start with the property address and add the parcel/APN, owner, document number, legal description, or date range if known.'),
        faq('Can I request property records by APN?', 'Yes. Parcel or APN information is often a strong identifier for county or municipal property systems.'),
        faq('What property records can I ask for?', 'Depending on the custodian, you may target assessor records, recorder documents, property files, ownership records, permits, planning records, and other identifiable records.'),
        faq('What if I do not know the parcel number?', 'The address and other known property identifiers can still provide a useful starting point. An APN can be added later if discovered.'),
      ],
    ),
  },
  {
    slug: 'code-enforcement-records',
    title: 'Code Enforcement Records Request',
    category: 'Property & Code Enforcement',
    intent: 'code enforcement records request',
    description: 'Create a focused public-records request for code violations, complaints, inspections, notices, photographs, permits, citations, communications, and enforcement history for a property or case.',
    bestFor: ['Code violation histories', 'Inspection records', 'Complaints and photographs', 'Notices, citations and enforcement files', 'Property-specific code records'],
    cta: 'Build a Code Enforcement Records Request',
    seo: seo(
      'Code Enforcement Records Request — Property Violations, Inspections & Case Files',
      'Create a focused code enforcement records request for property violations, complaints, inspections, notices, permits, citations, photos, communications, and enforcement history. Build and mail your request.',
      ['code enforcement records request', 'code enforcement public records request', 'request code enforcement records', 'code violation records request', 'property code enforcement records', 'code enforcement complaint records', 'code enforcement inspection records', 'code violation history request', 'property violation records', 'building code enforcement records', 'code enforcement case records', 'code enforcement records by address', 'code enforcement records by parcel number', 'code enforcement records by case number', 'code enforcement request template'],
      [
        faq('Can I request code enforcement records for a property?', 'Yes. Identify the property by address, parcel or APN, case number, violation number, or other identifiers and specify the categories of records sought.'),
        faq('What code enforcement records can I request?', 'Depending on the agency, you may request complaints, inspections, photographs or video, notices, citations, orders, permits, correspondence, abatement records, and other identifiable enforcement records.'),
        faq('Can I request code enforcement records by address?', 'Yes. An address is often a useful identifier. Adding an APN, case number, violation number, or date range can make the request more precise.'),
        faq('What if the agency only produces some of the records?', 'The workflow preserves the original request scope so the production can be reviewed for missing categories, references to unproduced records, gaps, and follow-up needs.'),
      ],
    ),
  },
  {
    slug: 'permit-inspection-records',
    title: 'Permit & Inspection Records',
    category: 'Property',
    intent: 'permit records request',
    description: 'Target permits, plans, inspection reports, correction notices, approvals, and related building-department records with project identifiers and date ranges.',
    bestFor: ['Building permits', 'Inspection reports', 'Plans', 'Correction notices'],
    cta: 'Request permit records',
    seo: seo(
      'Building Permit Records Request — Permits, Inspections, Plans & History',
      'Build a targeted property permit records request using an address, parcel/APN, permit number, owner, project, permit type, and date range.',
      ['property permit records request', 'building permit records request', 'permit records by address', 'permit records by APN', 'building permit history request', 'inspection records request', 'building inspection records', 'approved plans request', 'permit application records request', 'certificate of occupancy records', 'permit history request', 'historical building permit records'],
      [
        faq('What property permit records can I request?', 'The workflow can target permits, applications, inspections, approved plans, site plans, plan-review comments, correction notices, certificates of occupancy, permit history, and related correspondence.'),
        faq('What information helps locate permit records?', 'A property address, parcel/APN, permit number, owner or applicant, project description, and date range can make the search more precise.'),
        faq('Can I request approved building plans?', 'The request can specifically identify approved plans, drawings, specifications, plan sets, and revisions. Releasability depends on the agency and applicable law.'),
        faq('What if I only know the address and approximate project year?', 'Use the address, approximate date range, project description, owner or applicant name if known, and any permit details you already have.'),
      ],
    ),
  },
  {
    slug: 'government-communications-records',
    title: 'Government Emails & Communications Records',
    category: 'Communications',
    intent: 'government email records request',
    description: 'Build a precise request for government emails, attachments, texts, messaging, calendars, letters, meeting follow-up, and communications with outside parties using custodians, search terms, and date ranges.',
    bestFor: ['Government emails', 'Email attachments', 'Text and messaging records', 'Communications with contractors and developers', 'Calendar and meeting communications'],
    cta: 'Build a Government Communications Request',
    seo: seo(
      'Government Email & Communications Records Request',
      'Build a targeted government communications records request for emails, attachments, texts, messaging, calendars, and communications using custodians, keywords, projects, outside parties, and date ranges.',
      ['government email records request', 'government emails public records request', 'public records email request', 'request government emails', 'government communications records request', 'agency email records', 'government text messages public records', 'government text message records request', 'public records request emails and attachments', 'government communications request template', 'government emails by custodian', 'government emails by date range', 'government emails by keyword', 'public records email search terms', 'agency communications records'],
      [
        faq('How should I request government emails?', 'Identify the agency, date range, subject or project, likely custodians, and distinctive search terms. A focused request is easier to search and review.'),
        faq('Can I request government text messages?', 'Potentially. The workflow can separately identify text messages and agency messaging records where those communications are maintained and legally requestable.'),
        faq('Should email attachments be requested separately?', 'Yes. Identifying attachments explicitly helps preserve them as a production category and makes missing attachments easier to spot.'),
        faq('What if the agency says it found no responsive emails?', 'Preserve the exact request scope and search constraints. A follow-up can ask about custodians, systems, dates, or search terms without assuming whether records exist.'),
      ],
    ),
  },
  {
    slug: 'planning-records',
    title: 'Planning & Development Records',
    category: 'Planning',
    intent: 'planning records request',
    description: 'Request planning applications, staff reports, zoning materials, development correspondence, meeting records, and related agency files.',
    bestFor: ['Planning files', 'Zoning records', 'Development applications', 'Staff reports'],
    cta: 'Request planning records',
    seo: seo(
      'Planning Records Request — Zoning, Development Applications & Staff Reports',
      'Build a focused planning and development records request for zoning files, applications, staff reports, correspondence, meeting materials, permits, and project records.',
      ['planning records request', 'planning department records request', 'zoning records request', 'zoning file request', 'development application records request', 'planning application records', 'staff report request', 'land use records request', 'planning commission records request', 'development project records request', 'zoning public records request', 'planning records by address'],
      [
        faq('What planning records can I request?', 'You can identify planning applications, zoning materials, staff reports, project correspondence, meeting materials, resolutions, notices, and other records tied to a project or property.'),
        faq('Can I request planning records for a development project?', 'Yes. Use the project name, address, parcel/APN, applicant, project number, or date range to narrow the request.'),
        faq('Can I request zoning records by address?', 'Yes. An address plus parcel or project identifiers can help connect planning and zoning records to a specific property.'),
        faq('What if the project has changed names?', 'Include known names, applicant names, project numbers, addresses, and date ranges so the custodian can search across naming changes.'),
      ],
    ),
  },
  {
    slug: 'case-records',
    title: 'Records About a Specific Case',
    category: 'Case research',
    intent: 'records about a specific case',
    description: 'Build a case-centered request that connects names, addresses, case numbers, dates, departments, and referenced documents into one coherent records scope.',
    bestFor: ['Enforcement cases', 'Administrative cases', 'Agency investigations', 'Cross-department records'],
    cta: 'Build a case request',
    seo: seo(
      'Case Records Request — Build a Complete Government Case File Search',
      'Build a case-centered public records request using case numbers, people, properties, departments, dates, related documents, and referenced records.',
      ['case records request', 'case file records request', 'government case file request', 'agency case records', 'administrative case records request', 'investigation records request', 'enforcement case records', 'case records by number', 'case records by address', 'case records by name', 'request agency investigation records', 'public records case file'],
      [
        faq('How do I request records about a specific government case?', 'Identify the case number if known, agency or department, people or property involved, date range, and categories of records you want.'),
        faq('What if I do not know the case number?', 'Use the people, property, event, project, department, and date information available. A clear factual description can still provide a useful search anchor.'),
        faq('What are cross-referenced records?', 'A case file may refer to photographs, permits, correspondence, inspections, attachments, or other records held elsewhere. Explicitly identifying those categories improves production review.'),
        faq('What if records are spread across more than one department?', 'List the departments or custodians most likely to maintain responsive records and keep the case identifiers consistent across the request scope.'),
      ],
    ),
  },
  {
    slug: 'foia-request',
    title: 'FOIA / Federal Records Request',
    category: 'Federal',
    intent: 'how do I file a FOIA request',
    description: 'Prepare a federal records request with a clear description of the records, date range, custodians or systems when known, and the requester information needed for the agency.',
    bestFor: ['Federal agencies', 'FOIA requests', 'Federal records'],
    cta: 'Build a FOIA request',
    seo: seo(
      'FOIA Request — How to File a Federal Records Request',
      'Build a focused federal FOIA request with agency, records sought, date range, custodians, identifiers, search terms, and delivery preferences.',
      ['FOIA request', 'how to file a FOIA request', 'FOIA request template', 'FOIA records request', 'federal records request', 'request federal government records', 'FOIA letter', 'FOIA request example', 'federal public records request', 'FOIA request by agency', 'FOIA documents request', 'FOIA records search'],
      [
        faq('How do I file a FOIA request?', 'Identify the federal agency likely to maintain the records, describe the records with reasonable specificity, provide relevant dates and identifiers, and use the agency’s accepted submission channel.'),
        faq('What should a FOIA request include?', 'Identify the records sought, relevant time period, custodians or systems when known, distinctive search terms, and any requester or fee information the agency requires.'),
        faq('Can I ask a federal agency to search by name or keyword?', 'Yes. Names, project terms, document titles, case numbers, and other distinctive search terms can help the agency locate responsive records.'),
        faq('Is FOIA the law for state and local records?', 'Usually not. Federal FOIA applies to federal executive-branch agencies; state and local records are generally governed by applicable state or local public-records law.'),
      ],
    ),
  },
  {
    slug: 'birth-records',
    title: 'Birth Records Request',
    category: 'Vital records',
    intent: 'birth records request',
    description: 'Request birth certificates, registration records, amendments, and related vital records from the appropriate vital records office.',
    bestFor: ['Birth certificates', 'Vital records', 'Genealogy'],
    cta: 'Request birth records',
    seo: seo('Birth Records Request — Certificates & Registration Records', 'Build a birth records request for certificates, registration records, amendments, and related vital records.', ['birth records request','birth certificate request','request birth records','vital records birth'], [faq('How do I request birth records?','Identify the vital records office, the person on the record, date of birth, and place of birth.'), faq('Who can request birth records?','Access rules vary by state. The person named on the record, immediate family, or authorized representatives may be eligible.'), faq('What information helps locate a birth record?','The full name, date of birth, place of birth, and parent names are most useful.'), faq('Can I get a certified copy?','The request can specifically ask for a certified copy if you are eligible under applicable law.')]),
  },
  {
    slug: 'marriage-records',
    title: 'Marriage Records Request',
    category: 'Vital records',
    intent: 'marriage records request',
    description: 'Request marriage licenses, certificates, applications, and related vital records from the county clerk or vital records office.',
    bestFor: ['Marriage certificates', 'Marriage licenses', 'Vital records'],
    cta: 'Request marriage records',
    seo: seo('Marriage Records Request — Licenses & Certificates', 'Build a marriage records request for licenses, certificates, applications, and related vital records.', ['marriage records request','marriage certificate request','request marriage records','marriage license records'], [faq('How do I request marriage records?','Identify the county clerk or vital records office, the parties, and the marriage date or license number.'), faq('Where are marriage records held?','Typically at the county clerk office where the license was issued.'), faq('Can I get a certified copy?','The request can ask for a certified copy if you are eligible under applicable law.'), faq('What if I do not know the exact date?','Provide approximate dates and party names to help narrow the search.')]),
  },
  {
    slug: 'divorce-records',
    title: 'Divorce Records Request',
    category: 'Vital records',
    intent: 'divorce records request',
    description: 'Request divorce decrees, case files, and related family court records from the court or vital records office.',
    bestFor: ['Divorce decrees', 'Family court records', 'Vital records'],
    cta: 'Request divorce records',
    seo: seo('Divorce Records Request — Decrees & Case Files', 'Build a divorce records request for decrees, case files, and related family court records.', ['divorce records request','divorce decree request','request divorce records','divorce certificate'], [faq('How do I request divorce records?','Identify the court or vital records office, the parties, and the case number if known.'), faq('Are divorce records public?','Availability varies. Some records may be restricted, sealed, or confidential.'), faq('What is the difference between a decree and a certificate?','A divorce decree is the court judgment; a divorce certificate is a shorter vital-records summary.'), faq('Where are divorce records held?','Generally at the family court where the divorce was granted.')]),
  },
  {
    slug: 'death-records',
    title: 'Death Records Request',
    category: 'Vital records',
    intent: 'death records request',
    description: 'Request death certificates, registration records, and related vital records from the appropriate vital records office.',
    bestFor: ['Death certificates', 'Vital records', 'Genealogy'],
    cta: 'Request death records',
    seo: seo('Death Records Request — Certificates & Registration Records', 'Build a death records request for certificates, registration records, and related vital records.', ['death records request','death certificate request','request death records','vital records death'], [faq('How do I request death records?','Identify the vital records office, the deceased person, and date of death.'), faq('Who can request death records?','Access rules vary by state. Immediate family, authorized representatives, or those with a direct interest may be eligible.'), faq('What information helps locate a death record?','The full name, date of death, and place of death are most useful.'), faq('Can I get a certified copy?','The request can ask for a certified copy if you are eligible under applicable law.')]),
  },
  {
    slug: 'criminal-records',
    title: 'Criminal Records Request',
    category: 'Law enforcement & courts',
    intent: 'criminal records request',
    description: 'Request criminal case files, charges, court records, sentencing, probation, and related records for a specific case or person.',
    bestFor: ['Criminal case files', 'Court records', 'Sentencing records'],
    cta: 'Request criminal records',
    seo: seo('Criminal Records Request — Case Files, Charges & Court Records', 'Build a criminal records request for case files, charges, court records, sentencing, and related records.', ['criminal records request','criminal case file request','request criminal records','criminal court records'], [faq('How do I request criminal records?','Identify the court or agency, the person or case number, and the relevant time period.'), faq('Are criminal records public?','Many criminal court records are public, but some may be sealed or restricted.'), faq('Can I request sentencing records?','Yes, sentencing records and related disposition documents can be requested.'), faq('What if I do not know the case number?','Provide the person name, approximate date, and jurisdiction to help narrow the search.')]),
  },
  {
    slug: 'criminal-history',
    title: 'Criminal History Request',
    category: 'Law enforcement & courts',
    intent: 'criminal history request',
    description: 'Request criminal history records, rap sheets, background information, and related records from the appropriate agency.',
    bestFor: ['Criminal history', 'Rap sheets', 'Background records'],
    cta: 'Request criminal history',
    seo: seo('Criminal History Request — Rap Sheets & Background Records', 'Build a criminal history request for rap sheets, background records, and related records.', ['criminal history request','rap sheet request','criminal background records','request criminal history'], [faq('How do I request criminal history records?','Identify the agency (state police, DOJ, FBI), the person, and date of birth.'), faq('Can anyone request criminal history?','Access rules vary. Some states allow personal requests; others restrict to authorized parties.'), faq('What is a rap sheet?','A rap sheet is a criminal history record listing arrests, charges, and dispositions.'), faq('How long does it take?','Processing times vary by agency and request type.')]),
  },
  {
    slug: 'arrest-records',
    title: 'Arrest Records Request',
    category: 'Law enforcement & courts',
    intent: 'arrest records request',
    description: 'Request arrest reports, booking records, charging documents, and related law enforcement records.',
    bestFor: ['Arrest reports', 'Booking records', 'Charging documents'],
    cta: 'Request arrest records',
    seo: seo('Arrest Records Request — Booking & Arrest Records', 'Build an arrest records request for booking records, charging documents, and related law enforcement records.', ['arrest records request','booking records request','request arrest records','arrest report'], [faq('How do I request arrest records?','Identify the law enforcement agency, the person, and the arrest date or booking number.'), faq('Are arrest records public?','Availability varies by jurisdiction; some may be restricted or expunged.'), faq('Can I get mugshots?','Mugshots may be available but release policies vary by agency and state law.'), faq('What if I do not know the booking number?','Provide the person name and approximate arrest date.')]),
  },
  {
    slug: 'background-check-records',
    title: 'Background Check Records Request',
    category: 'Law enforcement & courts',
    intent: 'background check records request',
    description: 'Request background check records, screening reports, and related records from the agency that conducted or maintains the check.',
    bestFor: ['Background check reports', 'Screening records', 'Verification records'],
    cta: 'Request background check records',
    seo: seo('Background Check Records Request', 'Build a background check records request for screening reports and related records.', ['background check records request','request background check','background screening records'], [faq('How do I request background check records?','Identify the agency and the person who was screened.'), faq('Can I request my own background check?','Yes, you can generally request your own records.'), faq('What information is in a background check?','May include criminal history, employment verification, and education verification.'), faq('How long does it take?','Processing times vary by agency.')]),
  },
  {
    slug: 'military-records',
    title: 'Military Records Request',
    category: 'Personal records',
    intent: 'military records request',
    description: 'Request military service records, personnel files, discharge papers, and related military records.',
    bestFor: ['Service records', 'DD-214', 'Personnel files', 'Military awards'],
    cta: 'Request military records',
    seo: seo('Military Records Request — Service Records & DD-214', 'Build a military records request for service records, personnel files, discharge papers, and related records.', ['military records request','military service records','request DD-214','military personnel file','service records request'], [faq('How do I request military records?','Identify the agency (NPRC, VA, branch), the veteran, and service period.'), faq('What is a DD-214?','A DD Form 214 is the certificate of release or discharge from active duty.'), faq('Who can request military records?','The veteran or next of kin generally can. Some records are available under FOIA.'), faq('Where are military records held?','Most at the National Personnel Records Center (NPRC) in St. Louis.')]),
  },
  {
    slug: 'medical-records',
    title: 'Medical Records Request',
    category: 'Personal records',
    intent: 'medical records request',
    description: 'Request medical records, treatment histories, test results, and related health records from a healthcare provider.',
    bestFor: ['Medical records', 'Test results', 'Treatment histories'],
    cta: 'Request medical records',
    seo: seo('Medical Records Request — Health Records & Test Results', 'Build a medical records request for treatment histories, test results, and related health records.', ['medical records request','request medical records','health records request','patient records request','HIPAA records request'], [faq('How do I request medical records?','Identify the provider, patient name, and treatment period. HIPAA gives patients the right to access their records.'), faq('How long does a provider have to respond?','Under HIPAA, generally 30 days, with one 30-day extension allowed.'), faq('Can I be charged for copies?','Providers may charge reasonable, cost-based fees for copying.'), faq('What if the provider refuses?','You can file a complaint with HHS Office for Civil Rights.')]),
  },
  {
    slug: 'employment-records',
    title: 'Employment Records Request',
    category: 'Personal records',
    intent: 'employment records request',
    description: 'Request employment records, personnel files, payroll, and related employment records from an employer.',
    bestFor: ['Personnel files', 'Payroll records', 'Performance evaluations'],
    cta: 'Request employment records',
    seo: seo('Employment Records Request — Personnel Files & Payroll', 'Build an employment records request for personnel files, payroll, and related employment records.', ['employment records request','personnel file request','request employment records','payroll records request'], [faq('How do I request employment records?','Identify the employer, employee name, and employment period.'), faq('Can I request my own personnel file?','Many states give employees the right to inspect their personnel file.'), faq('What records can I request?','Personnel files, payroll, time and attendance, evaluations, and related records.'), faq('What if the employer refuses?','State labor laws vary on access rights and enforcement.')]),
  },
  {
    slug: 'education-records',
    title: 'Education Records Request',
    category: 'Personal records',
    intent: 'education records request',
    description: 'Request education records, transcripts, enrollment history, and related student records from a school or educational institution.',
    bestFor: ['Transcripts', 'Enrollment records', 'Student records'],
    cta: 'Request education records',
    seo: seo('Education Records Request — Transcripts & Student Records', 'Build an education records request for transcripts, enrollment history, and related student records.', ['education records request','transcripts request','request student records','FERPA records request','school records request'], [faq('How do I request education records?','Identify the school, student name, and enrollment period. FERPA governs access to student records.'), faq('Who can request education records?','Students and parents of minor students generally have access rights under FERPA.'), faq('Can I get my transcripts?','Yes, you can request transcripts directly from the school registrar.'), faq('What if the school refuses?','You can file a FERPA complaint with the U.S. Department of Education.')]),
  },
  {
    slug: 'records-follow-up',
    title: 'Records Follow-Up Request',
    category: 'Lifecycle',
    intent: 'records follow up request',
    description: 'Follow up on an unanswered, incomplete, or delayed records request with a targeted inquiry about status, missing items, and deadlines.',
    bestFor: ['Status inquiries', 'Missing records', 'Deadline enforcement'],
    cta: 'Build a follow-up',
    seo: seo('Records Follow-Up Request — Status & Missing Items', 'Build a follow-up request for an unanswered, incomplete, or delayed records request.', ['records follow up request','public records follow up','records request status','follow up on FOIA'], [faq('When should I follow up?','If the statutory response period has passed or the production appears incomplete.'), faq('What should a follow-up include?','The original request date, reference number, missing categories, and last contact date.'), faq('Can I ask about deadlines?','Yes, a follow-up can ask for confirmation of the response deadline and any extensions claimed.'), faq('What if the agency does not respond to the follow-up?','You may escalate to an appeal, an ombudsman, or a oversight body.')]),
  },
  {
    slug: 'records-denial-appeal',
    title: 'Records Denial / Appeal Request',
    category: 'Lifecycle',
    intent: 'records denial appeal',
    description: 'Appeal a records request denial by identifying the denied categories, stated exemption basis, and arguments for disclosure.',
    bestFor: ['Denial appeals', 'Exemption challenges', 'Disclosure arguments'],
    cta: 'Build an appeal',
    seo: seo('Records Denial Appeal — Challenge a Records Denial', 'Build an appeal for a records request denial by identifying denied categories, exemption basis, and disclosure arguments.', ['records denial appeal','appeal FOIA denial','public records appeal','records request denied'], [faq('How do I appeal a records denial?','Identify the agency, original request, denial date, stated exemption basis, and your argument for disclosure.'), faq('How long do I have to appeal?','Appeal deadlines vary by law. Federal FOIA generally gives 90 days; state deadlines vary.'), faq('What are common exemption bases?','Privacy, law enforcement, trade secrets, deliberative process, and other statutory exemptions.'), faq('What if the appeal is denied?','You may file a lawsuit under the applicable public records or FOIA statute.')]),
  },
  {
    slug: 'police-report',
    title: 'Police Report Request',
    category: 'Law enforcement & courts',
    intent: 'police report request',
    description: 'Request a specific police or incident report by report number, date, location, and involved parties.',
    bestFor: ['Incident reports', 'Accident reports', 'Traffic reports'],
    cta: 'Request a police report',
    seo: seo('Police Report Request — Get a Copy of an Incident Report', 'Build a police report request to get a copy of an incident report by report number, date, location, and involved parties.', ['police report request','get a police report','request police report','police report copy'], [faq('How do I get a copy of a police report?','Identify the law enforcement agency, report number, incident date, and location.'), faq('Can anyone get a police report?','Access varies. Involved parties, attorneys, and insurance companies often have access; some info may be redacted.'), faq('What if I do not know the report number?','Provide the incident date, location, and names of people involved to help locate the report.'), faq('Is there a fee?','Many agencies charge a fee for copies. The request can ask about the fee schedule.')]),
  },
  {
    slug: 'police-report-copy',
    title: 'Police Report Copy Request',
    category: 'Law enforcement & courts',
    intent: 'police report copy request',
    description: 'Request a certified or duplicate copy of a police report, including fees, format, and delivery preferences.',
    bestFor: ['Certified copies', 'Duplicate reports', 'Fee and format requests'],
    cta: 'Request a report copy',
    seo: seo('Police Report Copy Request — Get a Duplicate or Certified Copy', 'Build a request for a duplicate or certified copy of a police report with fee, format, and delivery preferences.', ['police report copy request','certified police report','duplicate police report','request copy of police report'], [faq('How do I get a certified copy of a police report?','Identify the records division and report number, and request a certified copy.'), faq('What is the difference between a regular and certified copy?','A certified copy includes an official seal or certification making it admissible as evidence.'), faq('How much does a copy cost?','Fees vary by agency. The request can ask about the fee schedule.'), faq('Can I get a digital copy?','Many agencies offer digital copies. Specify your format preference in the request.')]),
  },
  {
    slug: 'public-information-request',
    title: 'Public Information Request',
    category: 'Start here',
    intent: 'public information request',
    description: 'Request public information and government records under applicable public information laws.',
    bestFor: ['Public information', 'Government data', 'Agency records'],
    cta: 'Build a public information request',
    seo: seo('Public Information Request — Government Records & Information', 'Build a public information request for government records and information under applicable public information laws.', ['public information request','request public information','government information request','public records access'], [faq('What is a public information request?','A formal request for government records or information under applicable public information or open records law.'), faq('What information can I request?','Most government records are requestable, with exemptions for privacy, security, and certain legal protections.'), faq('How specific should my request be?','Describe the information with enough specificity for the agency to locate it.'), faq('Is there a cost?','Some agencies charge fees for copying or research time. Ask about the fee schedule if unsure.')]),
  },
  {
    slug: 'open-records-request',
    title: 'Open Records Request',
    category: 'Start here',
    intent: 'open records request',
    description: 'Request open records and government documents under state and local open records laws.',
    bestFor: ['Open records', 'State records', 'Local government records'],
    cta: 'Build an open records request',
    seo: seo('Open Records Request — State & Local Government Records', 'Build an open records request for state and local government records under applicable open records laws.', ['open records request','open records law','request open records','state open records'], [faq('What is an open records request?','A request for government records under state or local open records laws.'), faq('How is this different from FOIA?','FOIA applies to federal agencies; open records laws apply to state and local government.'), faq('How long does the agency have to respond?','Response times vary by state law, typically 3-10 business days.'), faq('Can the agency deny my request?','Yes, but they must cite the specific exemption. You can appeal.')]),
  },
  {
    slug: 'agency-records-request',
    title: 'Agency Records Request',
    category: 'Start here',
    intent: 'agency records request',
    description: 'Request records from a specific government agency with targeted record categories, custodians, and identifiers.',
    bestFor: ['Agency records', 'Department records', 'Targeted requests'],
    cta: 'Build an agency records request',
    seo: seo('Agency Records Request — Targeted Government Agency Records', 'Build a targeted agency records request with record categories, custodians, identifiers, and date ranges.', ['agency records request','request agency records','government agency records','agency documents request'], [faq('How do I request records from a specific agency?','Identify the agency, describe the records, provide date ranges and identifiers, and submit through the agency accepted channel.'), faq('What if I do not know which agency has the records?','Think about which agency handles the subject matter. You can also contact the agency records officer for guidance.'), faq('Can I request records from any agency?','Most government agencies are subject to public records laws. Some records may be exempt.'), faq('How specific should I be?','The more specific your request, the faster the agency can locate responsive records.')]),
  },
  {
    slug: 'government-documents-request',
    title: 'Government Documents Request',
    category: 'Start here',
    intent: 'government documents request',
    description: 'Request government documents, reports, publications, and official records from a government agency.',
    bestFor: ['Government documents', 'Official reports', 'Publications'],
    cta: 'Request government documents',
    seo: seo('Government Documents Request — Reports, Publications & Official Records', 'Build a government documents request for reports, publications, and official records from a government agency.', ['government documents request','request government documents','official documents request','government publications request'], [faq('How do I request government documents?','Identify the agency, describe the documents, provide dates and identifiers, and submit the request.'), faq('What types of documents can I request?','Reports, studies, publications, memoranda, directives, datasets, and other official records.'), faq('Are government documents always free?','Some are free; others may have copying or research fees depending on the agency.'), faq('Can I request electronic copies?','Many agencies provide electronic copies. Specify your preferred format in the request.')]),
  },
]
